"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-plugin-registry.js
 * Generated at: 2026-01-15T01:18:57.182Z
 * 
 * Only ACTIVE plugins are included.
 * Plugin info is read from each plugin's manifest.json
 */

import dynamic from "next/dynamic";
import { ComponentType } from "react";

const componentCache: Record<string, ComponentType<any> | null> = {};

function createSafeComponent(
    importFn: () => Promise<any>,
    fallback: ComponentType<any> = () => null
): ComponentType<any> {
    return dynamic(
        () => importFn().catch((err) => {
            console.warn("Plugin load failed:", err?.message || err);
            return { default: fallback };
        }),
        {
            loading: () => null,
            ssr: false,
        }
    );
}

const PLUGIN_DEFINITIONS: Record<string, () => Promise<any>> = {

};

export function isPluginAvailable(slug: string): boolean {
    return slug in PLUGIN_DEFINITIONS;
}

export function getPluginComponent(slug: string): ComponentType<any> | null {
    if (!isPluginAvailable(slug)) {
        return null;
    }
    if (componentCache[slug]) {
        return componentCache[slug];
    }
    const component = createSafeComponent(PLUGIN_DEFINITIONS[slug]);
    componentCache[slug] = component;
    return component;
}

export function getRegisteredPlugins(): string[] {
    return Object.keys(PLUGIN_DEFINITIONS);
}

/**
 * Initialize Plugin Hooks (e.g., extensions, form modifiers)
 */
export function loadPluginHooks() {
    if (typeof window === 'undefined') return;
    
    
}
