"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-plugin-registry.js
 * Generated at: 2026-01-14T22:05:50.323Z
 * 
 * Only ACTIVE plugins are included.
 * Plugin info is read from each plugin's manifest.json
 */

import dynamic from "next/dynamic";
import { ComponentType } from "react";

const componentCache: Record<string, ComponentType<any> | null> = {};

function createSafeComponent(
    importFn: () => Promise<any>,
    fallback: ComponentType<any> = () => null
): ComponentType<any> {
    return dynamic(
        () => importFn().catch((err) => {
            console.warn("Plugin load failed:", err?.message || err);
            return { default: fallback };
        }),
        {
            loading: () => null,
            ssr: false,
        }
    );
}

const PLUGIN_DEFINITIONS: Record<string, () => Promise<any>> = {
    "card-gallery": () => import("../../../backend/plugins/card-gallery/client/components/PromoCards"),
    "photo-carousel": () => import("../../../backend/plugins/photo-carousel/client/components/HeroCarousel"),
    "video-gallery": () => import("../../../backend/plugins/video-gallery/client/components/VideoCarousel"),
};

export function isPluginAvailable(slug: string): boolean {
    return slug in PLUGIN_DEFINITIONS;
}

export function getPluginComponent(slug: string): ComponentType<any> | null {
    if (!isPluginAvailable(slug)) {
        return null;
    }
    if (componentCache[slug]) {
        return componentCache[slug];
    }
    const component = createSafeComponent(PLUGIN_DEFINITIONS[slug]);
    componentCache[slug] = component;
    return component;
}

export function getRegisteredPlugins(): string[] {
    return Object.keys(PLUGIN_DEFINITIONS);
}

/**
 * Initialize Plugin Hooks (e.g., extensions, form modifiers)
 */
export function loadPluginHooks() {
    if (typeof window === 'undefined') return;
    
    
            import("../../../backend/plugins/mail-server/client/UserFormExtension").then(m => {
                // Auto-register any export starting with 'register'
                Object.keys(m).forEach(key => {
                    if (key.startsWith('register') && typeof m[key] === 'function') {
                        try { m[key](); } catch(e) { console.error('Error in hook mail-server:', e); }
                    }
                });
            });
}
