// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: scripts/generate-puck-plugin-registry.js
// Generated at: 2026-01-15T17:02:38.708Z
// Plugin info is read from each plugin's manifest.json



export const puckPluginComponents: Record<string, any> = {

};
