// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: scripts/generate-puck-plugin-registry.js
// Generated at: 2026-01-14T22:02:51.901Z
// Plugin info is read from each plugin's manifest.json

import * as CardGalleryPuck from "../../../backend/plugins/card-gallery/client/puck/CardGalleryPuck";
import * as PhotoCarouselPuck from "../../../backend/plugins/photo-carousel/client/puck/PhotoCarouselPuck";
import * as VideoGalleryPuck from "../../../backend/plugins/video-gallery/client/puck/VideoGalleryPuck";

export const puckPluginComponents: Record<string, any> = {
    "CardGallery": {
        ...CardGalleryPuck.puckComponentDef,
        render: CardGalleryPuck.default
    },
    "PhotoCarousel": {
        ...PhotoCarouselPuck.puckComponentDef,
        render: PhotoCarouselPuck.default
    },
    "VideoGallery": {
        ...VideoGalleryPuck.puckComponentDef,
        render: VideoGalleryPuck.default
    },
};
