import { describe, expect, it } from "vitest";
import { buildRevisionRestoreMessage } from "@/lib/revisionRestoreDescription";

describe("F4 revision restore disclosure", () => {
    it("names fields generated by the frozen snapshot, including plugin fields", () => {
        const message = buildRevisionRestoreMessage({
            restore: {
                compatible: true,
                legacy: false,
                schemaVersion: 1,
                codecVersion: 1,
                schemaFingerprint: "a".repeat(64),
                inactivePluginPolicy: "snapshot-authoritative",
                preservesUndeclaredFields: true,
                fields: [
                    { name: "title", description: "Editorial title", storage: "column", present: true, willClear: false },
                    { name: "pluginRating", description: "Plugin rating", storage: "meta", present: false, willClear: true },
                ],
            },
        }, "today");
        expect(message).toMatch(/Editorial title/);
        expect(message).toMatch(/Plugin rating/);
        expect(message).toMatch(/will be cleared/);
        expect(message).toMatch(/snapshot did not declare/);
        expect(message).toMatch(/unsaved changes/);
    });

    it("falls back to the complete legacy disclosure for an older backend", () => {
        const message = buildRevisionRestoreMessage({}, "yesterday");
        for (const phrase of ["Page layout", "Theme template", "Featured image", "SEO title", "SEO description", "Social image", "Search indexing preference"]) {
            expect(message).toContain(phrase);
        }
        expect(message).toMatch(/review thread/);
    });

    it("does not present an incompatible codec as restorable", () => {
        const message = buildRevisionRestoreMessage({
            restore: {
                compatible: false,
                legacy: false,
                schemaVersion: 1,
                codecVersion: 99,
                schemaFingerprint: null,
                inactivePluginPolicy: "snapshot-authoritative",
                preservesUndeclaredFields: true,
                fields: [],
                errorCode: "revision_codec_unsupported",
            },
        }, "today");
        expect(message).toMatch(/cannot be restored/);
        expect(message).toMatch(/No data will be changed/);
    });
});
