"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-admin-plugin-registry.js
 * Generated at: 2026-01-28T04:07:20.156Z
 * 
 * Plugin info is read from each plugin's manifest.json
 */

import dynamic from "next/dynamic";
import { useParams } from "next/navigation";
import { Suspense } from "react";

const PLUGIN_ADMIN_PAGES: Record<string, () => Promise<any>> = {
    "cards": () => import("../../../../../../backend/plugins/card-gallery/client/admin/page"),
    "conference-manager": () => import("../../../../../../backend/plugins/conference-manager/client/admin/page"),
    "db-migration": () => import("../../../../../../backend/plugins/db-migration/client/admin/page"),
    "emails": () => import("../../../../../../backend/plugins/mail-server/client/admin/page"),
    "carousels": () => import("../../../../../../backend/plugins/photo-carousel/client/admin/page"),
    "videos": () => import("../../../../../../backend/plugins/video-gallery/client/admin/page"),
};

function LoadingFallback() {
    return (
        <div className="p-8 flex items-center justify-center">
            <div className="text-center">
                <div className="inline-block w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                <p className="text-gray-500">Loading plugin...</p>
            </div>
        </div>
    );
}

function PluginNotFound({ slug }: { slug: string }) {
    return (
        <div className="p-8 text-center">
            <div className="text-6xl mb-4">🔌</div>
            <h1 className="text-2xl font-bold text-gray-800 mb-2">Plugin Not Found</h1>
            <p className="text-gray-600 mb-4">
                The plugin <code className="bg-gray-100 px-2 py-1 rounded">{slug}</code> is not installed.
            </p>
            <a href="/admin/plugins" className="text-blue-600 hover:underline">
                ← Back to Plugins
            </a>
        </div>
    );
}

export default function PluginAdminPage() {
    const params = useParams();
    const slug = params.slug as string;

    if (!PLUGIN_ADMIN_PAGES[slug]) {
        return <PluginNotFound slug={slug} />;
    }

    const PluginPage = dynamic(
        () => PLUGIN_ADMIN_PAGES[slug]().catch(() => ({
            default: () => <PluginNotFound slug={slug} />
        })),
        { loading: () => <LoadingFallback />, ssr: false }
    );

    return (
        <Suspense fallback={<LoadingFallback />}>
            <PluginPage />
        </Suspense>
    );
}
