"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-admin-plugin-registry.js
 * Generated at: 2026-07-18T14:43:42.731Z
 * 
 * Plugin info is read from each plugin's manifest.json
 */

import dynamic from "next/dynamic";
import { useParams } from "next/navigation";
import { useEffect, useState, Suspense } from "react";

const PLUGIN_ADMIN_PAGES: Record<string, () => Promise<any>> = {
    "tracking": () => import("../../../../../../backend/plugins/analytics-tag/client/admin/page"),
    "auctions": () => import("../../../../../../backend/plugins/auctions/client/admin/page"),
    "bookings": () => import("../../../../../../backend/plugins/bookings/client/admin/page"),
    "cards": () => import("../../../../../../backend/plugins/card-gallery/client/admin/page"),
    "conference-manager": () => import("../../../../../../backend/plugins/conference-manager/client/admin/page"),
    "contact-forms": () => import("../../../../../../backend/plugins/contact-forms/client/admin/page"),
    "cookie-consent": () => import("../../../../../../backend/plugins/cookie-consent/client/admin/page"),
    "downloads": () => import("../../../../../../backend/plugins/digital-downloads/client/admin/page"),
    "donations": () => import("../../../../../../backend/plugins/donations/client/admin/page"),
    "tickets": () => import("../../../../../../backend/plugins/event-tickets/client/admin/page"),
    "events-calendar": () => import("../../../../../../backend/plugins/events-calendar/client/admin/page"),
    "faq": () => import("../../../../../../backend/plugins/faq/client/admin/page"),
    "lightbox": () => import("../../../../../../backend/plugins/image-lightbox/client/admin/page"),
    "invoices": () => import("../../../../../../backend/plugins/invoices/client/admin/page"),
    "jobs": () => import("../../../../../../backend/plugins/job-board/client/admin/page"),
    "emails": () => import("../../../../../../backend/plugins/mail-server/client/admin/page"),
    "newsletter": () => import("../../../../../../backend/plugins/newsletter/client/admin/page"),
    "announcement": () => import("../../../../../../backend/plugins/notification-bar/client/admin/page"),
    "store": () => import("../../../../../../backend/plugins/online-store/client/admin/page"),
    "polls": () => import("../../../../../../backend/plugins/polls/client/admin/page"),
    "popups": () => import("../../../../../../backend/plugins/popup-builder/client/admin/page"),
    "restaurant": () => import("../../../../../../backend/plugins/restaurant-menu/client/admin/page"),
    "share": () => import("../../../../../../backend/plugins/social-share/client/admin/page"),
    "testimonials": () => import("../../../../../../backend/plugins/testimonials/client/admin/page"),
    "vendor-marketplace": () => import("../../../../../../backend/plugins/vendor-marketplace/client/admin/page"),
    "youtube": () => import("../../../../../../backend/plugins/youtube-videos/client/admin/page"),
};

// Maps the URL admin-slug to the plugin's on-disk FOLDER id, so admin.css / manifest.json are
// fetched from the correct /plugins/<folder>/ path (the slug and folder often differ).
const PLUGIN_ADMIN_DIRS: Record<string, string> = {
    "tracking": "analytics-tag",
    "auctions": "auctions",
    "bookings": "bookings",
    "cards": "card-gallery",
    "conference-manager": "conference-manager",
    "contact-forms": "contact-forms",
    "cookie-consent": "cookie-consent",
    "downloads": "digital-downloads",
    "donations": "donations",
    "tickets": "event-tickets",
    "events-calendar": "events-calendar",
    "faq": "faq",
    "lightbox": "image-lightbox",
    "invoices": "invoices",
    "jobs": "job-board",
    "emails": "mail-server",
    "newsletter": "newsletter",
    "announcement": "notification-bar",
    "store": "online-store",
    "polls": "polls",
    "popups": "popup-builder",
    "restaurant": "restaurant-menu",
    "share": "social-share",
    "testimonials": "testimonials",
    "vendor-marketplace": "vendor-marketplace",
    "youtube": "youtube-videos",
};

function LoadingFallback() {
    return (
        <div className="p-8 flex items-center justify-center">
            <div className="text-center">
                <div className="inline-block w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4 font-black"></div>
                <p className="text-gray-500">Loading plugin...</p>
            </div>
        </div>
    );
}

function PluginNotFound({ slug }: { slug: string }) {
    return (
        <div className="p-8 text-center">
            <div className="text-6xl mb-4">🔌</div>
            <h1 className="text-2xl font-bold text-gray-800 mb-2">Plugin Not Found</h1>
            <p className="text-gray-600 mb-4">
                The plugin <code className="bg-gray-100 px-2 py-1 rounded">{slug}</code> is not installed.
            </p>
            <a href="/admin/plugins" className="text-blue-600 hover:underline font-bold">
                ← Back to Plugins
            </a>
        </div>
    );
}

export default function PluginAdminPage() {
    const params = useParams();
    const slug = params.slug as string;
    const [hasCss, setHasCss] = useState(false);
    const [themeStyle, setThemeStyle] = useState("");

    // Static assets are served under the plugin's FOLDER id, which can differ from the URL slug.
    const dir = PLUGIN_ADMIN_DIRS[slug] || slug;
    const cssUrl = `/plugins/${dir}/client/admin/admin.css`;

    useEffect(() => {
        if (!slug) return;
        setHasCss(false);
        setThemeStyle("");

        // Check for admin.css existence
        fetch(cssUrl, { method: "HEAD" })
            .then((res) => {
                if (res.ok) setHasCss(true);
            })
            .catch(() => {});

        // Fetch manifest.json to check for style/theme fields. The plugin admin page is already
        // trusted first-party JS, but this string reaches a dangerouslySetInnerHTML sink, so strip
        // characters that could break out of the injected <style> ('}' rule breakout, '<' tag
        // breakout, '@'/';' extra rules) — defense in depth, not the sandbox boundary.
        fetch(`/plugins/${dir}/manifest.json`)
            .then((res) => res.json())
            .then((manifest) => {
                const clean = (s: unknown) => String(s).replace(/[<>{}@;]/g, "");
                if (typeof manifest.style === "string" && manifest.style) {
                    setThemeStyle(manifest.style.replace(/</g, ""));
                } else if (manifest.theme && typeof manifest.theme === "object") {
                    const vars = Object.entries(manifest.theme)
                        .filter(([key]) => /^[a-zA-Z0-9-]+$/.test(key))
                        .map(([key, val]) => `--plugin-${key}: ${clean(val)};`)
                        .join(" ");
                    if (vars) setThemeStyle(`.plugin-admin-${slug} { ${vars} }`);
                }
            })
            .catch(() => {});
    }, [slug, cssUrl, dir]);

    if (!PLUGIN_ADMIN_PAGES[slug]) {
        return <PluginNotFound slug={slug} />;
    }

    const PluginPage = dynamic(
        () => PLUGIN_ADMIN_PAGES[slug]().catch(() => ({
            default: () => <PluginNotFound slug={slug} />
        })),
        { loading: () => <LoadingFallback />, ssr: false }
    );

    return (
        <div className={`plugin-admin-wrapper plugin-admin-${slug} h-full overflow-y-auto custom-scrollbar`}>
            {themeStyle && <style dangerouslySetInnerHTML={{ __html: themeStyle }} />}
            {hasCss && <link rel="stylesheet" href={cssUrl} />}
            <Suspense fallback={<LoadingFallback />}>
                <PluginPage />
            </Suspense>
        </div>
    );
}
