"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-plugin-registry.js
 * Generated at: 2026-01-28T04:07:20.059Z
 * 
 * HYBRID LOADING SYSTEM:
 * - Development: Static imports for hot reload
 * - Production: Pre-compiled bundles for instant activation
 */

import dynamic from "next/dynamic";
import { ComponentType } from "react";

// Detect environment
const IS_DEV = process.env.NODE_ENV === 'development';

const componentCache: Record<string, ComponentType<any> | null> = {};

// ============================================
// DEVELOPMENT: Static Imports (Hot Reload)
// ============================================
const DEV_DEFINITIONS: Record<string, () => Promise<any>> = {
    "card-gallery": () => import("../../../backend/plugins/card-gallery/client/components/PromoCards"),
    "conference-manager": () => import("../../../backend/plugins/conference-manager/client/admin/page"),
    "db-migration": () => import("../../../backend/plugins/db-migration/client/admin/page"),
    "mail-server": () => import("../../../backend/plugins/mail-server/client/admin/page"),
    "photo-carousel": () => import("../../../backend/plugins/photo-carousel/client/components/HeroCarousel"),
    "video-gallery": () => import("../../../backend/plugins/video-gallery/client/components/VideoCarousel"),
};

// ============================================
// PRODUCTION: Pre-compiled Bundle Loader
// ============================================
async function loadProductionBundle(slug: string): Promise<any> {
    try {
        const response = await fetch(`/api/v1/plugins/${slug}/bundle?type=admin`);
        if (!response.ok) {
            console.warn(`[PluginLoader] Bundle not found for ${slug}`);
            return { default: () => null };
        }
        
        const bundleCode = await response.text();
        const blob = new Blob([bundleCode], { type: 'application/javascript' });
        const blobUrl = URL.createObjectURL(blob);
        
        try {
            const module = await import(/* webpackIgnore: true */ blobUrl);
            URL.revokeObjectURL(blobUrl);
            return module;
        } catch (err) {
            console.error(`[PluginLoader] Failed to evaluate bundle for ${slug}:`, err);
            URL.revokeObjectURL(blobUrl);
            return { default: () => null };
        }
    } catch (err) {
        console.error(`[PluginLoader] Failed to fetch bundle for ${slug}:`, err);
        return { default: () => null };
    }
}

// List of plugins with pre-compiled bundles
const PRODUCTION_PLUGINS: string[] = ["card-gallery", "conference-manager", "db-migration", "mail-server", "photo-carousel", "video-gallery"];

// ============================================
// Unified Plugin Loader
// ============================================
function createSafeComponent(
    importFn: () => Promise<any>,
    fallback: ComponentType<any> = () => null
): ComponentType<any> {
    return dynamic(
        () => importFn().catch((err) => {
            console.warn("Plugin load failed:", err?.message || err);
            return { default: fallback };
        }),
        {
            loading: () => null,
            ssr: false,
        }
    );
}

export function isPluginAvailable(slug: string): boolean {
    if (IS_DEV) {
        return slug in DEV_DEFINITIONS;
    }
    return PRODUCTION_PLUGINS.includes(slug);
}

export function getPluginComponent(slug: string): ComponentType<any> | null {
    if (!isPluginAvailable(slug)) {
        return null;
    }
    if (componentCache[slug]) {
        return componentCache[slug];
    }
    
    let component: ComponentType<any>;
    
    if (IS_DEV) {
        // Development: Use static imports (hot reload works)
        component = createSafeComponent(DEV_DEFINITIONS[slug]);
    } else {
        // Production: Use pre-compiled bundles (no next build needed)
        component = createSafeComponent(() => loadProductionBundle(slug));
    }
    
    componentCache[slug] = component;
    return component;
}

export function getRegisteredPlugins(): string[] {
    if (IS_DEV) {
        return Object.keys(DEV_DEFINITIONS);
    }
    return PRODUCTION_PLUGINS;
}

/**
 * Initialize Plugin Hooks (e.g., extensions, form modifiers)
 */
export function loadPluginHooks() {
    if (typeof window === 'undefined') return;
    
    
            import("../../../backend/plugins/mail-server/client/UserFormExtension").then(m => {
                // Auto-register any export starting with 'register'
                Object.keys(m).forEach(key => {
                    const exportFn = (m as any)[key];
                    if (key.startsWith('register') && typeof exportFn === 'function') {
                        try { exportFn(); } catch(e) { console.error('Error in hook mail-server:', e); }
                    }
                });
            });
}
