"use client";

/**
 * AUTO-GENERATED FILE - Do not edit directly!
 * 
 * Generated by: scripts/generate-plugin-registry.js
 * Generated at: 2026-07-18T14:43:42.187Z
 * 
 * HYBRID LOADING SYSTEM:
 * - Development: Static imports for hot reload
 * - Production: Pre-compiled bundles for instant activation
 */

import dynamic from "next/dynamic";
import { ComponentType } from "react";

// Detect environment
const IS_DEV = process.env.NODE_ENV === 'development';

const componentCache: Record<string, ComponentType<any> | null> = {};

// ============================================
// DEVELOPMENT: Static Imports (Hot Reload)
// ============================================
const DEV_DEFINITIONS: Record<string, () => Promise<any>> = {
    "analytics-tag": () => import("../../../backend/plugins/analytics-tag/client/admin/page"),
    "auctions": () => import("../../../backend/plugins/auctions/client/admin/page"),
    "bookings": () => import("../../../backend/plugins/bookings/client/admin/page"),
    "card-gallery": () => import("../../../backend/plugins/card-gallery/client/components/PromoCards"),
    "conference-manager": () => import("../../../backend/plugins/conference-manager/client/admin/page"),
    "contact-forms": () => import("../../../backend/plugins/contact-forms/client/admin/page"),
    "cookie-consent": () => import("../../../backend/plugins/cookie-consent/client/admin/page"),
    "digital-downloads": () => import("../../../backend/plugins/digital-downloads/client/admin/page"),
    "donations": () => import("../../../backend/plugins/donations/client/admin/page"),
    "event-tickets": () => import("../../../backend/plugins/event-tickets/client/admin/page"),
    "events-calendar": () => import("../../../backend/plugins/events-calendar/client/admin/page"),
    "faq": () => import("../../../backend/plugins/faq/client/admin/page"),
    "image-lightbox": () => import("../../../backend/plugins/image-lightbox/client/admin/page"),
    "invoices": () => import("../../../backend/plugins/invoices/client/admin/page"),
    "job-board": () => import("../../../backend/plugins/job-board/client/admin/page"),
    "mail-server": () => import("../../../backend/plugins/mail-server/client/admin/page"),
    "newsletter": () => import("../../../backend/plugins/newsletter/client/admin/page"),
    "notification-bar": () => import("../../../backend/plugins/notification-bar/client/admin/page"),
    "online-store": () => import("../../../backend/plugins/online-store/client/admin/page"),
    "polls": () => import("../../../backend/plugins/polls/client/admin/page"),
    "popup-builder": () => import("../../../backend/plugins/popup-builder/client/admin/page"),
    "restaurant-menu": () => import("../../../backend/plugins/restaurant-menu/client/admin/page"),
    "social-share": () => import("../../../backend/plugins/social-share/client/admin/page"),
    "testimonials": () => import("../../../backend/plugins/testimonials/client/admin/page"),
    "vendor-marketplace": () => import("../../../backend/plugins/vendor-marketplace/client/admin/page"),
    "youtube-videos": () => import("../../../backend/plugins/youtube-videos/client/admin/page"),
};

// ============================================
// PRODUCTION: Pre-compiled Bundle Loader
// ============================================
async function loadProductionBundle(slug: string): Promise<any> {
    try {
        const response = await fetch(`/api/v1/plugins/${slug}/bundle?type=admin`);
        if (!response.ok) {
            console.warn(`[PluginLoader] Bundle not found for ${slug}`);
            return { default: () => null };
        }
        
        const bundleCode = await response.text();
        const blob = new Blob([bundleCode], { type: 'application/javascript' });
        const blobUrl = URL.createObjectURL(blob);
        
        try {
            const module = await import(/* webpackIgnore: true */ blobUrl);
            URL.revokeObjectURL(blobUrl);
            return module;
        } catch (err) {
            console.error(`[PluginLoader] Failed to evaluate bundle for ${slug}:`, err);
            URL.revokeObjectURL(blobUrl);
            return { default: () => null };
        }
    } catch (err) {
        console.error(`[PluginLoader] Failed to fetch bundle for ${slug}:`, err);
        return { default: () => null };
    }
}

// List of plugins with pre-compiled bundles
const PRODUCTION_PLUGINS: string[] = ["analytics-tag", "auctions", "bookings", "card-gallery", "conference-manager", "contact-forms", "cookie-consent", "digital-downloads", "donations", "event-tickets", "events-calendar", "faq", "image-lightbox", "invoices", "job-board", "mail-server", "newsletter", "notification-bar", "online-store", "polls", "popup-builder", "restaurant-menu", "social-share", "testimonials", "vendor-marketplace", "youtube-videos"];

// ============================================
// Unified Plugin Loader
// ============================================
function createSafeComponent(
    importFn: () => Promise<any>,
    fallback: ComponentType<any> = () => null
): ComponentType<any> {
    return dynamic(
        () => importFn().catch((err) => {
            console.warn("Plugin load failed:", err?.message || err);
            return { default: fallback };
        }),
        {
            loading: () => null,
            ssr: false,
        }
    );
}

export function isPluginAvailable(slug: string): boolean {
    if (IS_DEV) {
        return slug in DEV_DEFINITIONS;
    }
    return PRODUCTION_PLUGINS.includes(slug);
}

export function getPluginComponent(slug: string): ComponentType<any> | null {
    if (!isPluginAvailable(slug)) {
        return null;
    }
    if (componentCache[slug]) {
        return componentCache[slug];
    }
    
    let component: ComponentType<any>;
    
    if (IS_DEV) {
        // Development: Use static imports (hot reload works)
        component = createSafeComponent(DEV_DEFINITIONS[slug]);
    } else {
        // Production: Use pre-compiled bundles (no next build needed)
        component = createSafeComponent(() => loadProductionBundle(slug));
    }
    
    componentCache[slug] = component;
    return component;
}

export function getRegisteredPlugins(): string[] {
    if (IS_DEV) {
        return Object.keys(DEV_DEFINITIONS);
    }
    return PRODUCTION_PLUGINS;
}

/**
 * Initialize Plugin Hooks (e.g., extensions, form modifiers)
 */
export function loadPluginHooks(): Promise<void> {
    if (typeof window === 'undefined') return Promise.resolve();
    const loaders: Promise<any>[] = [
    
        import("../../../backend/plugins/mail-server/client/UserFormExtension").then(m => {
            // Auto-register any export starting with 'register'
            Object.keys(m).forEach(key => {
                const exportFn = (m as any)[key];
                if (key.startsWith('register') && typeof exportFn === 'function') {
                    try { exportFn(); } catch(e) { console.error('Error in hook mail-server:', e); }
                }
            });
        }),
    ];
    // A failed hook chunk must be VISIBLE to the caller: initPlugins un-latches its run-once guard on
    // rejection so a later mount retries (hook registration is idempotent via keys, so retrying the
    // already-loaded plugins is safe). allSettled: one broken plugin never blocks the others.
    return Promise.allSettled(loaders).then((results) => {
        const failed = results.filter(r => r.status === 'rejected') as PromiseRejectedResult[];
        failed.forEach(f => console.error('Plugin hook bundle failed to load:', f.reason));
        if (failed.length) throw new Error(failed.length + ' plugin hook bundle(s) failed to load');
    });
}
