// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: scripts/generate-puck-plugin-registry.js
// Generated at: 2026-07-18T14:43:43.486Z
// Plugin info is read from each plugin's manifest.json

import * as AuctionsPuck from "../../../backend/plugins/auctions/client/puck/AuctionsPuck";
import * as BookingsPuck from "../../../backend/plugins/bookings/client/puck/BookingsPuck";
import * as BreadcrumbsPuck from "../../../backend/plugins/breadcrumbs/client/puck/BreadcrumbsPuck";
import * as CardGalleryPuck from "../../../backend/plugins/card-gallery/client/puck/CardGalleryPuck";
import * as ContactFormsPuck from "../../../backend/plugins/contact-forms/client/puck/ContactFormsPuck";
import * as DigitalDownloadsPuck from "../../../backend/plugins/digital-downloads/client/puck/DigitalDownloadsPuck";
import * as DonationsPuck from "../../../backend/plugins/donations/client/puck/DonationsPuck";
import * as EventTicketsPuck from "../../../backend/plugins/event-tickets/client/puck/EventTicketsPuck";
import * as EventsCalendarPuck from "../../../backend/plugins/events-calendar/client/puck/EventsCalendarPuck";
import * as FaqPuck from "../../../backend/plugins/faq/client/puck/FaqPuck";
import * as InvoicesPuck from "../../../backend/plugins/invoices/client/puck/InvoicesPuck";
import * as JobBoardPuck from "../../../backend/plugins/job-board/client/puck/JobBoardPuck";
import * as NewsletterPuck from "../../../backend/plugins/newsletter/client/puck/NewsletterPuck";
import * as OnlineStorePuck from "../../../backend/plugins/online-store/client/puck/OnlineStorePuck";
import * as PollsPuck from "../../../backend/plugins/polls/client/puck/PollsPuck";
import * as RelatedPostsPuck from "../../../backend/plugins/related-posts/client/puck/RelatedPostsPuck";
import * as RestaurantMenuPuck from "../../../backend/plugins/restaurant-menu/client/puck/RestaurantMenuPuck";
import * as SocialSharePuck from "../../../backend/plugins/social-share/client/puck/SocialSharePuck";
import * as TableOfContentsPuck from "../../../backend/plugins/table-of-contents/client/puck/TableOfContentsPuck";
import * as TestimonialsPuck from "../../../backend/plugins/testimonials/client/puck/TestimonialsPuck";
import * as VendorMarketplacePuck from "../../../backend/plugins/vendor-marketplace/client/puck/VendorMarketplacePuck";
import * as YoutubeVideosPuck from "../../../backend/plugins/youtube-videos/client/puck/YoutubeVideosPuck";

export const puckPluginComponents: Record<string, any> = {
    "Auctions": {
        ...AuctionsPuck.puckComponentDef,
        render: AuctionsPuck.default
    },
    "Bookings": {
        ...BookingsPuck.puckComponentDef,
        render: BookingsPuck.default
    },
    "Breadcrumbs": {
        ...BreadcrumbsPuck.puckComponentDef,
        render: BreadcrumbsPuck.default
    },
    "CardGallery": {
        ...CardGalleryPuck.puckComponentDef,
        render: CardGalleryPuck.default
    },
    "ContactForms": {
        ...ContactFormsPuck.puckComponentDef,
        render: ContactFormsPuck.default
    },
    "DigitalDownloads": {
        ...DigitalDownloadsPuck.puckComponentDef,
        render: DigitalDownloadsPuck.default
    },
    "Donations": {
        ...DonationsPuck.puckComponentDef,
        render: DonationsPuck.default
    },
    "EventTickets": {
        ...EventTicketsPuck.puckComponentDef,
        render: EventTicketsPuck.default
    },
    "EventsCalendar": {
        ...EventsCalendarPuck.puckComponentDef,
        render: EventsCalendarPuck.default
    },
    "Faq": {
        ...FaqPuck.puckComponentDef,
        render: FaqPuck.default
    },
    "Invoices": {
        ...InvoicesPuck.puckComponentDef,
        render: InvoicesPuck.default
    },
    "JobBoard": {
        ...JobBoardPuck.puckComponentDef,
        render: JobBoardPuck.default
    },
    "Newsletter": {
        ...NewsletterPuck.puckComponentDef,
        render: NewsletterPuck.default
    },
    "OnlineStore": {
        ...OnlineStorePuck.puckComponentDef,
        render: OnlineStorePuck.default
    },
    "Polls": {
        ...PollsPuck.puckComponentDef,
        render: PollsPuck.default
    },
    "RelatedPosts": {
        ...RelatedPostsPuck.puckComponentDef,
        render: RelatedPostsPuck.default
    },
    "RestaurantMenu": {
        ...RestaurantMenuPuck.puckComponentDef,
        render: RestaurantMenuPuck.default
    },
    "SocialShare": {
        ...SocialSharePuck.puckComponentDef,
        render: SocialSharePuck.default
    },
    "TableOfContents": {
        ...TableOfContentsPuck.puckComponentDef,
        render: TableOfContentsPuck.default
    },
    "Testimonials": {
        ...TestimonialsPuck.puckComponentDef,
        render: TestimonialsPuck.default
    },
    "VendorMarketplace": {
        ...VendorMarketplacePuck.puckComponentDef,
        render: VendorMarketplacePuck.default
    },
    "YoutubeVideos": {
        ...YoutubeVideosPuck.puckComponentDef,
        render: YoutubeVideosPuck.default
    },
};
